# Generated by Django 5.1.6 on 2025-02-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#2f61a1', max_length=7),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#014f86', max_length=7),
        ),
    ]
