# Generated by Django 5.1.6 on 2025-02-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapi', '0004_alter_event_user_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
