name: Django Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        ls
        python -m pip install --upgrade pip
        chmod +x startup.sh
        ./startup.sh
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test accounts.tests
        python manage.py test contacts.tests
        python manage.py test calendarapi.tests
